services:
  db: #use docker debug in terminal to get a docker console inside the container
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
